#!/bin/bash

if grep -q "/dev/zram0" /proc/swaps; then
    echo "zram is already configured"
else
    total_mem=$(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')
    zram_size=$(echo "$total_mem * 0.55" | bc | cut -d'.' -f1)

    echo "$zram_size" > /sys/block/zram0/disksize
    echo "100" > /proc/sys/vm/swappiness
    echo "lz4" > /sys/block/zram0/comp_algorithm
    echo "0" > /proc/sys/vm/page-cluster
    echo "false" > /sys/kernel/mm/swap/vma_ra_enabled

    mkswap /dev/zram0
    swapon -p -3 /dev/zram0
fi

[ -e "/sys/kernel/furilabs/palmrejectionmode/common_node/" ] && chown furios:furios /sys/kernel/furilabs/palmrejectionmode/common_node/*mode
[ -e "/sys/class/flashlight/mt-flash-led1/" ] && chown furios:furios /sys/class/flashlight/mt-flash-led1/*
[ -e "/sys/class/flashlight/mt-flash-led2/" ] && chown furios:furios /sys/class/flashlight/mt-flash-led2/*

while [ "`getprop vendor.connsys.driver.ready`" != "yes" ]; do
    sleep 1
done

sleep 3

echo 1 > /dev/wmtWifi

while [ ! -e /sys/class/ieee80211/phy0 ]; do
    sleep 1
done

iw phy phy0 wowlan enable magic-packet

echo "0xFF:0x03" > /proc/net/wlan/dbgLevel

setprop ctl.stop statsd

while [ ! -e /dev/binderfs/anbox-binder ]; do
    sleep 1
done

chmod 666 /dev/binderfs/anbox-*

chown furios:furios /dev/binderfs/anbox-*

while [ ! -e /sys/class/leds/vibrator/activate ]; do
    sleep 1
done

chown furios:furios /sys/class/leds/vibrator/*

[ -e "/sys/class/leds/green/" ] && chown furios:furios /sys/class/leds/green/*
[ -e "/sys/class/flashlight_core/flashlight/" ] && chown furios:furios /sys/class/flashlight_core/flashlight/*
[ -e "/sys/class/leds/lcd-backlight/" ] && chown furios:furios /sys/class/leds/lcd-backlight/*

exit 0
