#!/bin/bash

while [ "`getprop vendor.connsys.driver.ready`" != "yes" ]; do
    sleep 1
done

sleep 3

echo 1 > /dev/wmtWifi

while [ ! -e /sys/class/ieee80211/phy0 ]; do
    sleep 1
done

iw phy phy0 wowlan enable magic-packet

echo "0xFF:0x03" > /proc/net/wlan/dbgLevel

exit 0
